version: '3.7'

services:
  romance-service:
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - ./src:/romance-service/src
    ports:
      - 3100:3100
    env_file:
      - ./.env.docker

  romance-mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'romance'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306

  romance-redis:
    image: redis:latest
    ports:
      - 6379:6379
