version: '3.7'

services:
  romance-service:
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - ./src:/romance-service/src
    restart: always
    ports:
      - 80:3100
    env_file:
      - ./.env.docker

  romance-mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'romance'
      MYSQL_ROOT_PASSWORD: 'root'
    restart: always
    ports:
      - 3306:3306

  romance-redis:
    image: redis:latest
    volumes: #redis 마운트할 볼륨 설정
      - ./redis/redis.conf:/redis/redis.conf
    restart: always
    ports:
      - 6379:6379
